### ISSUE TITLE
build using 3.9.2 fails

### ISSUE THREAD

**Issue by adventmedia** [AckerApple/angular-file#102]
Updated packages to current version (3.9.2 according to package.json). Building project fails:
(using current version of Angular, 15.2.5)
Rolled back to 3.7.0, builds ok

`Error: node_modules/angular-file/file-upload/ngf.directive.d.ts:76:12 - error TS2300: Duplicate identifier 'ɵfac'.

76     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<ngf, never>;
              ~~~~


Error: node_modules/angular-file/file-upload/ngf.directive.d.ts:77:12 - error TS2300: Duplicate identifier 'ɵdir'.

77     static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<ngf, never, never, {}, {}, never, never, false, never>;
              ~~~~

Error: node_modules/angular-file/file-upload/ngfBackground.directive.d.ts:11:12 - error TS2300: Duplicate identifier 'ɵfac'.

11     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<ngfBackground, never>;
              ~~~~


Error: node_modules/angular-file/file-upload/ngfBackground.directive.d.ts:12:12 - error TS2300: Duplicate identifier 'ɵdir'.

12     static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<ngfBackground, never, never, {}, {}, never, never, false, never>;
              ~~~~

Error: node_modules/angular-file/file-upload/ngfFormData.directive.d.ts:16:12 - error TS2300: Duplicate identifier 'ɵfac'.

16     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<ngfFormData, never>;
              ~~~~


Error: node_modules/angular-file/file-upload/ngfFormData.directive.d.ts:17:12 - error TS2300: Duplicate identifier 'ɵdir'.

17     static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<ngfFormData, never, never, {}, {}, never, never, false, never>;
              ~~~~

Error: node_modules/angular-file/file-upload/ngfSrc.directive.d.ts:11:12 - error TS2300: Duplicate identifier 'ɵfac'.

11     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<ngfSrc, never>;
              ~~~~


Error: node_modules/angular-file/file-upload/ngfSrc.directive.d.ts:12:12 - error TS2300: Duplicate identifier 'ɵdir'.

12     static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<ngfSrc, never, never, {}, {}, never, never, false, never>;
              ~~~~

Error: node_modules/angular-file/file-upload/ngfUploadStatus.directive.d.ts:11:12 - error TS2300: Duplicate identifier 'ɵfac'.

11     static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<ngfUploadStatus, never>;
              ~~~~


Error: node_modules/angular-file/file-upload/ngfUploadStatus.directive.d.ts:12:12 - error TS2300: Duplicate identifier 'ɵdir'.

12     static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<ngfUploadStatus, never, never, {}, {}, never, never, false, never>;
              ~~~~

`

**Comment by AckerApple** [comment]
I've dealt with this before in my other packages, I will address within 2 days max. Thank you so much for testing and reporting

**Comment by AckerApple** [comment]
Please try 3.9.3

**Comment by adventmedia** [comment]
same build errors, I'm afraid

**Comment by AckerApple** [comment]
Ok I will attempt to update where I test to Angular 15 to see if I can reproduce

**Comment by warisanwar** [comment]
Hello @AckerApple ,
We're facing the same issue as well with version 3.9.3,
Can you please prioritize and look into this?

Reference ss:
![image](https://github.com/AckerApple/angular-file/assets/28192108/13064a69-23f7-44d6-822d-302110ce9f9d)

**Comment by AckerApple** [comment]
The issue has been fixed with the release of 4.0.2

Please test, confirm, and close issue

@warisanwar thanks for reminding me to get back to this.

🌕 🌖 🌗  🌘  🌑 🌒  🌓 🌔 🌕

**Comment by AckerApple** [comment]
Oh hey, issue was: When upgrading from older version of Angular you need to clear out your distribution folder so that old files no longer exist as they can be auto read and in my case it made Angular load two sets of TypeScript files

[stackoverflow for the win](https://stackoverflow.com/questions/73141268/angular-13-update-duplicate-identifier-error)

**Comment by rafawalter** [comment]
Build fixed with versions 4.0.2 and 3.7.0

Thanks @AckerApple

**Comment by adventmedia** [comment]
fixed with 4.0.2!
